### ISSUE TITLE
meaning behind "checked" in test script demo

### ISSUE THREAD

**Issue by billylaw8** [transcript/samsa2#20]
Hi, 
I'm trying to run the test program "test_of_master_script_tiny.bash" and I've had to edit a bunch already (fill in all the bash vars, remove weird quotes around things), but this one takes the cake.

What's the meaning behind "checked"?  It's sprinkled throughout the code like a command, but it's not actually a program call.  What is it supposed to have been?

**Comment by transcript** [comment]
Hi billytaj,

Sorry about the delay in responding - "checked" is a function defined in the common.sh script (https://github.com/transcript/samsa2/blob/master/bash_scripts/lib/common.sh).  It runs the specified program unless the run is specified as a "dry run".  If a run is a dry run, the program doesn't actually execute (to save time and not generate outputs).  

Otherwise, it simply executes the called program and logs if there are any errors.

In terms of running the test_of_master_script_tiny, what do you mean by "fill in all the bash vars"?  A lot of those bash vars are defined in another script, and shouldn't need to be specified explicitly.
