### ISSUE TITLE
trimming for adaptors

### ISSUE THREAD

**Issue by seb951** [transcript/samsa2#21]
In the trimmomatic step of the pipeline (e.g.: Line 108 of https://github.com/transcript/samsa2/blob/master/bash_scripts/master_script.sh), there is no cleaning of adaptor contamination. I think this should be included by default as suggested by trimmomatic. http://www.usadellab.org/cms/?page=trimmomatic

Is there any reason not to include it? In addition, what is the reasoning for doing the trimming after the merging? Intuitively, I feel that it would make more sense to trim, then merge (i.e. you don't want to merge sequence based on adaptor contamination) ?

thanks,

**Comment by transcript** [comment]
This is a good point.  Similarly, I've needed to update Trimmomatic to run in paired-end mode if files are paired-end, and single-end mode otherwise.

This is now updated, as of commit "master de19db3".  Master_script executes Trimmomatic first, followed by PEAR (if applicable).  Additionally, the script should check if the reverse file exists when running Trimmomatic, and will switch to single-end mode if that's needed.
