### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by billylaw8** [transcript/samsa2#24]
Hi, 
I'm trying to install your pipeline, and I'm running into an error with the package_installation.bash script.
It's having issues with line 32. 
> package_installation.bash: line 32: package_installation.bash/../bash_scripts/lib/common.sh: Not a directory

any way to get around this?

**Comment by transcript** [comment]
Hi Billy,

Yes, there's a solution to this!  The installation script works if called from OUTSIDE the setup_and_test/ directory.

If you're in the base samsa2/ directory, run:

`bash setup_and_test/package_installation.bash`

and things should work.  It turns out that the relative path doesn't like being called from its direct location.

Let me know if this doesn't work.
Sam
