### ISSUE TITLE
Different database?

### ISSUE THREAD

**Issue by rachaelantwis** [transcript/samsa2#4]
Hello,
We want to use a different database (NR) for the pipeline but we've encountered a few issues. The pipeline doesn't progress from step 4 to step 5 when we change the database. Also we need to produce a custom NR database that only contains bacterial and fungal hits - do you know if this is possible?
Many thanks

**Comment by transcript** [comment]
Hi Rachael,

You should be able to use a custom database for this, yes - if you download the non-redundant files from RefSeq for bacteria (ftp://ftp.ncbi.nlm.nih.gov/refseq/release/bacteria/) and download the fungi protein annotations (ftp://ftp.ncbi.nlm.nih.gov/refseq/release/fungi/) and concatenate them together, you should be able to use as that as your DIAMOND reference database without problems.

(RefSeq fungi doesn't have a non-redundant database, likely due to the significantly lower number of total sequences.)

Are you getting an error when the pipeline fails to progress from step 4 to step 5?  Is it creating the $starting_location/step_4_output/ directory?  Are there files created inside?

**Comment by rachaelantwis** [comment]
Thanks very much for your quick response. We tried the pipeline with RefSeq but we were getting the majority of hits from hospital-associated bacteria and the samples are from trees! So we wanted to try a different database that was potentially less human-focussed. We seem to be getting better hits now.

However, it’s falling down at step 5 – the aggregation step. We're getting lots outputted to stderr, and then failure as follows:

Traceback (most recent call last):
  File “{path_to_samsa2}/python_scripts/DIAMOND_analysis_counter.py", line 156, in <module>
    db_org = split_db_org[1] + " " + split_db_org[2]

Perhaps there's a difference in ‘expected’ format of nr vs RefSeq?

Many thanks

**Comment by transcript** [comment]
Hmm, the format of a RefSeq file (grabbed a fungi one) looks identical to the nonredundant files. 

Quick sanity check - can you try cloning the SAMSA2 git repo again and rerun?  I just tried this with the most recent version of SAMSA2 and a RefSeq fungi protein file on a clean install and got no errors.

If you get the same error, could you upload the first 100 lines or so (`head -100 db_file > head.txt`) to this thread, and I can take a look?

**Comment by transcript** [comment]
For anyone consulting this in the future, it seems like the issue was resolved on the SAMSA Google group ([https://groups.google.com/forum/#!topic/samsa-bioinformatics-group/e95ywgN526I](https://groups.google.com/forum/#!topic/samsa-bioinformatics-group/e95ywgN526I)).  I'm closing this issue, although adding the BLAST NR database may be a future enhancement.

**Comment by mradz19** [comment]
@transcript Hey Sam, I am interested in using the Refseq fungal database on some of my samples. I have downloaded all the files in ftp://ftp.ncbi.nlm.nih.gov/refseq/release/fungi/. Am I correct that I only need the fna files? Do I just need to concatenate these then go through the same process of converting them to a DIAMOND database as outlined in the samsa documents?

**Comment by transcript** [comment]
Hey @mradz19, yup, you've got it right!  You should just need to concatenate the files.

You may want to check the headers and ensure that they're the same structure as the RefSeq bacteria files - that is, it should look like:

`>RefSeq_ID_number description of the function [Organism_genus organism_species]
`

**Comment by mradz19** [comment]
@transcript Thanks Sam, just confirming is it both RNA and genomic fna files or just the RNA ones I should use?

Also looking at the RNA fna files they are structured this way:
>XM_007754329.1 Cladophialophora yegresii CBS 114405 hypothetical protein partial mRNA

How can I change it to match the structure above?

**Comment by transcript** [comment]
@mradz19 Ideally, you'd want to use the protein sequences, since DIAMOND maps DNA alignments to protein.  I'd see if you could find those, first.

Looking at the RNA fna files, those are a different structure, which is concerning because it means the later parsing scripts won't work on them.  You'd need to run some sort of converting script (warning, pseudo-python ahead):

```
for line in infile:
      if ">" in line[0]:
            split = line.strip().split(" ", 5)
            outfile.write(" ".join(">", split[0], split[5], "[", split[1], split[2], split[3], split[4]))
            outfile.write("\n")
      else:
            outfile.write(line)
```

The idea being that this would loop through and put the organism name in brackets after the function name.  Of course, this may fail if the organism name is fewer or more than 4 words long.

Does this make sense?  I'm not sure of your code fluency, so let me know if it's not clear.

**Comment by mradz19** [comment]
@transcript Unfortunately my code fluency is basically non-existent. 

Ahh ok, so should I be working with the protein.faa files then? The protein faa files are structured like this:

>XP_007752233.1 hypothetical protein A1O7_00001 [Cladophialophora yegresii CBS 114405]

Which looks more like what you mentioned above.
