### ISSUE TITLE
DIAMOND_analysis_counter.py issue

### ISSUE THREAD

**Issue by marco91sol** [transcript/samsa2#49]
To whom it may concern,

I have created myfile.daa , then I obtain a BLAST m 8 data table (through diamond view). 
Then, I'd like to aggregate results considering the organism through: 
**$python2 DIAMOND_analysis_counter.py –I final_output –D uniprot_sprot.dmnd –O**
I have tried, but then as output, I receive this: 
WARNING: need to specify either organism results (with -O flag in command) or functional results (with -F flag in command)

What am I missing? 

Thanks,
Marco

**Comment by transcript** [comment]
Hi Marco,

Interesting.  I'll test this, but my first item is you will want to provide the .faa version of the reference database (with the -D command), rather than the DIAMOND-encrypted version.

I'll figure out if it's missing the -O command for some reason when parsing the ARGV.

Sam

**Comment by transcript** [comment]
Hi Marco,

Found the issue - it looks like you're using an em-dash (longer dash) before the O, while the program looks for single dashes.  Unfortunately, Python doesn't like the em-dashes you've got, so I can't really update the code easily to check for them.

This is assuming that the command you copied in is direct - you may want to paste it in a `code block` in order to avoid any formatting.

I'm not sure how you're running this command (is it through a shell script?), but you may want to convert it to plain ASCII to see if there's any missing or unexpected characters.

Sam
