### ISSUE TITLE
Trim and merge OR merge and trim?

### ISSUE THREAD

**Issue by monaparizadeh** [transcript/samsa2#5]
Hi Sam,

I'd like to know the reason that you trim assembled reads (and so you treat them as single-end sequences), instead of first trimming them as paired-end reads and then merge them. 

I'd also like to thank you for the nice documentation.

Mona

**Comment by transcript** [comment]
Hi Mona,

I wanted to preserve as many reads as possible - by assembling before quality-filtering, I hoped to preserve some read information in case one read in a pair turns out to have some low-quality regions.  The reads would be merged and then trimmed, instead of being fully discarded.

An alternative approach is to run Trimmomatic in a paired-end manner before merging read pairs.  This could slightly reduce some of the low-quality sequences, at the cost of slightly fewer reads making it through preprocessing.

Another option (that currently isn't yet implemented, but is on my radar) is to merge the unpaired forward reads with the paired reads, keeping more reads in the pipeline.

Best,
Sam

**Comment by monaparizadeh** [comment]
Hi Sam, 

I see! Actually, when I got my sequences, they have already been trimmed. So in this case, I think I should skip the trimming step. But, I really like your idea of merging the unpaired and paired reads! Looking forward to seeing the results, and once again thanks for sharing your pipeline.

Best regards,
Mona
