### ISSUE TITLE
update

### ISSUE THREAD

**Issue by yjiakang** [transcript/samsa2#80]
Thanks for your awesome pipeline. I saw that the last update of your pipeline was by 2021. Is it suitalbe for data today also?

**Comment by transcript** [comment]
Hi yjiakang,

You can still use this pipeline today, yes, although I'll note that the functional categorization SEED Subsystems database has not been updated since the mid-2010s and is growing increasingly outdated.  The RefSeq annotations are all still valid and up-to-date.

If you're looking for an alternative, you could also check out HUMAnN2, which gets a bit more love than this pipeline.
